# Generated by Django 4.2.6 on 2023-10-31 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boardapp', '0002_board_category_board_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='board_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
