# Generated by Django 4.2.6 on 2023-11-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_likes_alter_post_file_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='삭제됨 여부'),
        ),
    ]
