# Generated by Django 4.2.6 on 2023-11-04 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_deleted',
        ),
    ]
